language: node_js
node_js:
  - 14
script:
  - eslint 'src/**'
  - npm run test
  - npm run build
deploy:
  provider: codedeploy
  revision_type: github
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  application: codedeploy-app
  deployment_group: codedeploy-app-group
  region: us-east-1
  wait_until_deployed: true
  on:
    branch: master