version: 0.0
os: linux
files:
  - source: /
    destination: /home/app
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before-install-hook.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after-install-hook.sh
      timeout: 300