version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before-install-hook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install-hook.sh
      timeout: 300
      runas: root